#screen dimensions
WIDTH = 1500   
HEIGHT = 1000

#CONSTANTS
G =  11 #adjusted

#Spaceship
FORCE = 45000*2
HEALTH = 100
MASS = 300
ROTATE_SPEED = 250
MAX_SPEED = 200


#Bullets
BULLET_SPEED = 500
BULLET_LIFE_SPAN = 1.5
FIRERATE = 7 #bullets per second
DAMAGE = 20
AMMO_MULTIPLIER_LENGTH = 10


DS_TIME_LENGTH = 10

#TIME FREEZE
TIME_FREEZE_TIME = 4

#PHASE SHIFT
PS_fire_rate = 7
PHASE_SHIFT_POWER = 300
PORTAL_COOLDOWN = 1.5


#PROTON WAVE
GROWTH_SPEED = 600
PW_fire_rate = 15
PW_LIFE_TIME = 0.7
PW_power_up_length = 20
#ASTEROIDS
MASS_BIG = 400
MASS_MEDIUM = 200
MASS_SMALL = 100

ASTEROID_SPAWN_OFFSET = 20

HEALTH_BIG = 40
HEALTH_MEDIUM = 25
HEALTH_SMALL = 5

MIN_SPAWN_DISTANCE = 150
ASTEROID_ROTATE_SPEED = 2